# Project: Reportes
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = src/main.o src/ArmamentoPesado.o src/MotorReportes.o src/RecursoMilitar.o src/TrajeCombate.o
LINKOBJ  = src/main.o src/ArmamentoPesado.o src/MotorReportes.o src/RecursoMilitar.o src/TrajeCombate.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/Einll/OneDrive/Documentos/Germa66/cpp/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++" -I"C:/Users/Einll/OneDrive/Documentos/Germa66/cpp/include"
BIN      = Reportes.exe
CXXFLAGS = $(CXXINCS) -std=gnu++17
CFLAGS   = $(INCS) -std=gnu++17
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

src/main.o: src/main.cpp
	$(CPP) -c src/main.cpp -o src/main.o $(CXXFLAGS)

src/ArmamentoPesado.o: src/ArmamentoPesado.cpp
	$(CPP) -c src/ArmamentoPesado.cpp -o src/ArmamentoPesado.o $(CXXFLAGS)

src/MotorReportes.o: src/MotorReportes.cpp
	$(CPP) -c src/MotorReportes.cpp -o src/MotorReportes.o $(CXXFLAGS)

src/RecursoMilitar.o: src/RecursoMilitar.cpp
	$(CPP) -c src/RecursoMilitar.cpp -o src/RecursoMilitar.o $(CXXFLAGS)

src/TrajeCombate.o: src/TrajeCombate.cpp
	$(CPP) -c src/TrajeCombate.cpp -o src/TrajeCombate.o $(CXXFLAGS)
